name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to the pub.dev repository

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add your dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Add this line for linting

flutter:
  uses-material-design: true

  # Add your assets here (e.g. images, fonts, etc.)
  assets:
    - assets/images/

# For analysis options
analysis_options:
  include: package:flutter_lints/flutter.yaml
